// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mux4to1_HH_
#define _mux4to1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct mux4to1 : public sc_module {
    // Port declarations 11
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<2> > sel_V;
    sc_in< sc_lv<1> > d0_V;
    sc_in< sc_lv<1> > d1_V;
    sc_in< sc_lv<1> > d2_V;
    sc_in< sc_lv<1> > d3_V;
    sc_out< sc_lv<1> > y_V;
    sc_out< sc_logic > y_V_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    mux4to1(sc_module_name name);
    SC_HAS_PROCESS(mux4to1);

    ~mux4to1();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<2> > sel_V_read_read_fu_58_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_sel_V_read_read_fu_58_p2();
    void thread_y_V();
    void thread_y_V_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
